name: pawlly_employee
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.2.6+27

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3

  nb_utils: ^7.0.5
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  share_plus: ^10.1.0
  stream_transform: ^2.1.0
  custom_date_range_picker: ^1.1.0
  omni_datetime_picker: ^2.0.5

  # SOCIAL LOGIN
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.2.1
  permission_handler: ^11.3.1

  # State Management
  get: ^4.6.6

  # Payment
  #flutter_stripe: ^10.1.1

  #Storage
  get_storage: ^2.1.1

  #intent
  android_intent_plus: ^5.2.0

  datepicker_dropdown: ^0.1.5
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  country_picker: ^2.0.26

  # MAP
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0

  #PhotoViewGallery
  photo_view: ^0.15.0

  #SHIMMER
  shimmer: ^3.0.0

  flutter_localizations:
    sdk: flutter
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/images/services/
    - assets/images/pet_profile/
    - assets/images/notification/
    - assets/icons/profile_icons/
    - assets/icons/navigation/
    - assets/icons/service_icons/
    - assets/lottie/
    - assets/images/emp_icon/
    - assets/images/auth_images/
